#!/usr/bin/env bash

if [ ! -n "${HUGOUP_HOME+x}" ]; then

  PRG="$0"
  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
  done


  HUGOUP_HOME=`dirname "$PRG"`
  HUGOUP_HOME=`cd "$HUGOUP_HOME" && pwd`
fi

 
# build classpath from all jars in lib
if [ -f /usr/bin/cygpath ]; then
  CP=.
  for i in "$HUGOUP_HOME"/corn*.jar; do
    i=`cygpath --windows "$i"`
    CP="$CP;$i"
  done
  for i in "$HUGOUP_HOME"/lib/*.jar; do
    i=`cygpath --windows "$i"`
    CP="$CP;$i"
  done
else
  if [[ $(uname) = MINGW* ]]; then
    CP_SEPARATOR=";"
  else
    CP_SEPARATOR=":"
  fi
  CP=.
  for i in "$HUGOUP_HOME"/hugoup*.jar; do
    CP="$CP""$CP_SEPARATOR""$i"
  done
  for i in "$HUGOUP_HOME"/lib/*.jar; do
    CP="$CP""$CP_SEPARATOR""$i"
  done
fi

JAVA_OPTS="${JAVA_OPTS-}"

java -cp "$CP" $JAVA_OPTS com.ajkaandrej.hugoup.Main ${1+"$@"}

